### ISSUE TITLE
Internal documentation and onboarding overhaul

### ISSUE THREAD

**Issue by UZ9** [GTBitsOfGood/juno#88]
## Context
Juno currently lacks a streamlined way of onboarding new developers, both in understanding the project conceptually and specific documentation for Juno's services. This ticket aims to significantly improve the developer's experience via a refactoring of much of the Juno's documentation.

## Tasks
- [x] Fix Juno README instructions mentioning nonexistent docker compose (it's now split)
- [x] Add READMEs for all Juno services (instead of the default nest)
- [x] Collect all of the existing diagrams we have of Juno and modify/add as needed--this will help with streamlining the onboarding process
- [x] Keep a main overview of how each repository relates to another, as we're currently lacking a bit on this end

**Comment by UZ9** [comment]
Docker development moved to a separate ticket (#89)
