### ISSUE TITLE
Migrate package manager from yarn to pnpm

### ISSUE THREAD

**Issue by UZ9** [GTBitsOfGood/juno#89]
# Context
Juno currently utilizes `yarn` for all node package management, workflows, and controlling external scripts. Due to the limited performance of both `yarn` and `npm`, using `pnpm` will drastically reduce project setup times up to [2x](https://pnpm.io/). So far in personal testing I have experienced a (60s -> 18s) reduction when running `pnpm install`. 

# Tasks
- [x] Switch all `package.json` files to pnpm
- [x] Migrate all docker development files to pnpm
- [x]  Switch documentation to use `pnpm`
